// ============================================
// antd v6 主题：数值与 tokens.scss 同源，改颜色时两边一起改
// 主色 #DE5F0E 固定（品牌锁死）。但它只用于图标/装饰/焦点环/图表主色：白字压在上面只有 3.65:1，14px 文字不过 WCAG AA。实色按钮底走 action=#C5530A（4.55:1），品牌色文字走 text=#A84709（5.88:1）。
// 2026-09 起：中性/语义色对齐设计现场（Arco 系），品牌橙三层不变。
// ============================================
import type { ThemeConfig } from 'antd';

/** 给 JS 侧用的尺寸：组件里算高度时用这个，不要把 px 再硬写一遍 */
export const SXWL_LAYOUT = {
  headerHeight: 56,
  sidebarWidth: 224,
  sidebarCollapsedWidth: 56,
  contentPadding: 24,
  tableRow: 48,
  controlHeight: 36,
} as const;

/** 给 JS 侧用的颜色：图表 / canvas / SVG paint 用，禁止在 tsx 里再写十六进制 */
export const SXWL_COLOR = {
  brand500: '#DE5F0E',
  brandAction: '#C5530A',
  brandText: '#A84709',
  brandSubtle: '#FFF7ED',
  brandSelected: '#FDE8D5',
  brandBorder: '#F9C7A3',
  textHeading: '#1D2129',
  textBody: '#4E5969',
  textSecondary: '#86909C',
  textTertiary: '#A9AEB8',
  textInverse: '#FFFFFF',
  bgContainer: '#FFFFFF',
  bgSubtle: '#F7F8FA',
  bgPage: '#FAFAFA',
  border: '#E5E6EB',
  borderStrong: '#C9CDD4',
  divider: '#E5E6EB',
  success: '#00B42A',
  successText: '#009A29',
  successSubtle: '#E8FFEA',
  warning: '#FF7D00',
  warningText: '#D25F00',
  warningSubtle: '#FFF7E8',
  danger: '#F53F3F',
  dangerText: '#CB2634',
  dangerSubtle: '#FFECE8',
  chartSeries: ['#DE5F0E', '#0FC6C2', '#722ED1', '#F7BA1E', '#00B42A', '#F53F3F', '#D91AD9', '#86909C'],
  chartGrid: '#E5E6EB',
  chartAxisText: '#86909C',
} as const;

export const SXWL_ANTD_THEME: ThemeConfig = {
  token: {
    colorPrimary: '#C5530A',
    colorPrimaryHover: '#A84709',
    colorPrimaryActive: '#8A3A07',
    colorLink: '#A84709',
    colorLinkHover: '#C5530A',
    colorText: '#4E5969',
    colorTextSecondary: '#86909C',
    colorTextTertiary: '#A9AEB8',
    colorTextQuaternary: '#C9CDD4',
    colorTextPlaceholder: '#C9CDD4',
    colorBgLayout: '#FAFAFA',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorFillAlter: '#F7F8FA',
    controlItemBgHover: '#F2F3F5',
    controlItemBgActive: '#FDE8D5',
    colorBorder: '#E5E6EB',
    colorBorderSecondary: '#F2F3F5',
    colorSuccess: '#00B42A',
    colorSuccessText: '#009A29',
    colorSuccessBg: '#E8FFEA',
    colorWarning: '#FF7D00',
    colorWarningText: '#D25F00',
    colorWarningBg: '#FFF7E8',
    colorError: '#F53F3F',
    colorErrorText: '#CB2634',
    colorErrorBg: '#FFECE8',
    colorInfo: '#165DFF',
    colorInfoText: '#0E42D2',
    colorInfoBg: '#E8F3FF',
    fontFamily: "-apple-system, 'Segoe UI', Roboto, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif",
    fontSize: 14,
    lineHeight: 1.5715,
    borderRadius: 8,
    controlHeight: 36,
    boxShadowSecondary: '0 4px 12px rgba(29, 33, 41, 0.08), 0 2px 4px rgba(29, 33, 41, 0.04)',
  },
  components: {
    Button: { fontWeight: 500, primaryShadow: 'none', defaultShadow: 'none' },
    Card: { borderRadiusLG: 12, boxShadowTertiary: 'none' },
    Table: {
      // 表头不铺灰底：靠字重 + 一条底线分层。颜色一律走这里，不要再在 scss 里覆写 .ant-table
      headerBg: '#FFFFFF',
      headerColor: '#86909C',
      headerSplitColor: 'transparent',
      rowHoverBg: '#F7F8FA',
      rowSelectedBg: '#FFF7ED',
      rowSelectedHoverBg: '#FDE8D5',
      borderColor: '#F2F3F5',
      // 行高 48 = 上下 padding 12 + 22 文本行；列宽是按 inline 16 精调的，再抬会挤折行
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
    },
    Layout: {
      headerHeight: 56,
      headerPadding: '0 24px',
      headerBg: '#FFFFFF',
      siderBg: '#FFFFFF',
      bodyBg: '#FAFAFA',
    },
    Menu: {
      itemHeight: 32,
      itemBorderRadius: 6,
      itemSelectedBg: '#FDE8D5',
      itemSelectedColor: '#A84709',
      subMenuItemBg: 'transparent',
      iconSize: 16,
    },
    Modal: { borderRadiusLG: 12, boxShadow: '0 12px 32px rgba(29, 33, 41, 0.10), 0 4px 8px rgba(29, 33, 41, 0.04)' },
    Tabs: { horizontalItemPadding: '12px 16px' },
    Tag: { borderRadiusSM: 6 },
  },
};
