<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sxwl</groupId>
        <artifactId>sxwl-boot-module</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>sxwl-boot-module-system</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--
            监控系统业务模块
            <p>提供服务器运行状态采集、JVM 性能监控、Redis/DB 连接池监控等业务能力。</p>
        -->
        <dependency>
            <groupId>com.sxwl</groupId>
            <artifactId>sxwl-boot-module-monitor</artifactId>
        </dependency>
        <!-- Spring Boot Starter Data Redis（Redis 监控） -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxwl</groupId>
            <artifactId>sxwl-boot-config-sse</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxwl</groupId>
            <artifactId>sxwl-boot-config-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxwl</groupId>
            <artifactId>sxwl-boot-config-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxwl</groupId>
            <artifactId>sxwl-boot-config-mybatis</artifactId>
        </dependency>
    </dependencies>

</project>